spring:
  jpa:
    show-sql: true
  application:
    name: search
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/sba?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  servlet:
    context-path: /search
  port: 8085
  
eureka:
  client:
    service-url:
      defaultZone: http://sba.eureka:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate:
        SQL: DEBUG

feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000